import type { Metadata } from "next";
import { Poppins, Madimi_One } from "next/font/google";
import "./globals.css";
import { Carrossel } from "@/components/sections/Carrossel";
import { Footer } from "@/components/ui/Footer";
import { Navbar } from "@/components/ui/Navbar";
import { Toaster } from "sonner";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const madimiOne = Madimi_One({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-madimi-one",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Portfolio - Carol Magdalena",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.svg?v=2",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${madimiOne.variable} bg-[#F7F7F7] antialiased flex flex-col min-h-screen`}
      >
        <Navbar />
        {children}
        <Toaster />
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
